<robot name="foxy_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_width" value="0.07"/>
  <xacro:property name="base_length" value="0.13"/>
  <xacro:property name="base_height" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheel_separation" value="0.101"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.04"/>

  <xacro:property name="caster_radius" value="0.009"/>
  <xacro:property name="caster_zoff" value="0.032"/>
  <xacro:property name="caster_xoff" value="-0.043"/>

  <xacro:include filename="$(find foxy_description)/urdf/utils.xacro"/>

  <xacro:macro name="wheel" params="prefix parent x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="0.05" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(wheel_separation/2)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- params description for xacro component -->
  <!-- root_frame: name of the root link frame -->
  <xacro:macro name="foxy_base" params="root_frame">

    <material name="grey">
      <color rgba="0.7 0.7 0.7 1" />
    </material>
    <material name="green">
      <color rgba="0 0.6 0 1" />
    </material>
    <material name="white">
      <color rgba="1 1 1 1" />
    </material>

    <link name="base_footprint">
      <xacro:box_inertia m="0.5" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <link name="${root_frame}">
      <visual>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <geometry>
          <box size="0.6 0.4 0.2" />
        </geometry>
        <material name="green" />
      </visual>
      <collision>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_joint" type="fixed">
      <parent link="${root_frame}" />
      <child link="base_footprint" />
      <origin xyz="0 0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0" />
    </joint>

    <xacro:wheel prefix="left_wheel" parent="${root_frame}" x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="right_wheel" parent="${root_frame}" x_reflect="1" y_reflect="-1" />

    <link name="caster_wheel">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <material name="grey" />
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
      </collision>
      <xacro:sphere_inertia m="0.01" r="${caster_radius}"/>
    </link>

    <joint name="base_caster_wheel_joint" type="fixed">
      <parent link="${root_frame}" />
      <child link="caster_wheel" />
      <origin xyz="${caster_xoff} 0 -${(wheel_radius+wheel_zoff)-caster_radius}" rpy="0 0 0" />
    </joint>
  </xacro:macro>

</robot>
